#!/usr/bin/env python

import argparse
import time
import random

parser = argparse.ArgumentParser()
parser.add_argument('--sleep', type=int)
parser.add_argument('--outfile')
args = vars(parser.parse_args())

if args['sleep']:
    time.sleep(args['sleep'])

if args['outfile']:
    with open(args['outfile'], 'w') as outfile:
        outfile.write('{}\n'.format(args['outfile']))
else:
    print(random.randint(1, 1000))
